@startuml

actor User


User -->  Telegram_bot : make_an_order()
Telegram_bot --> Server : add_order_to_list()
Server --> Navigation_system : process_order()
Navigation_system --> Camera : get_extruder_location()
Camera --> Navigation_system : extruder_location
Navigation_system --> Camera : get_bot_location()
Camera --> Navigation_system : bot_location
Navigation_system --> Camera : get_user_location()
Camera --> Navigation_system : user_location
Navigation_system --> Bot : send_route()
Bot --> User : follow_to_user()
User --> Bot : give a cap
Bot --> Extruder : follow_to_extruder()
Extruder --> start_pouring
start_pouring --> stop_pouring
stop_pouring --> Bot : cap_is_full()
Bot --> User : follow_to_user()
Bot --> Server : send_success_status()


@enduml