@startuml

actor User


User -->  Telegram_bot : make_an_order()
Telegram_bot --> Server : add_order_to_list()
Server --> OpenCV_server : process_order()
OpenCV_server --> Camera : get_extruder_location()
Camera --> OpenCV_server : extruder_location
OpenCV_server --> Camera : get_bot_location()
Camera --> OpenCV_server : bot_location
OpenCV_server --> Camera : get_user_location()
Camera --> OpenCV_server : user_location
OpenCV_server --> Bot : send_route()
Bot --> User : follow_to_user()
User --> Bot : give a cap
Bot --> Extruder : follow_to_extruder()
Extruder --> start_pouring
start_pouring --> stop_pouring
stop_pouring --> Bot : cap_is_full()
Bot --> User : follow_to_user()
Bot --> Server : send_success_status()


@enduml