@startuml

actor User
Camera --> Camera : configure()
Move --> ControlSystem : calibration()
ControlSystem --> FooCmdReciver: run()
FooCmdReciver --> Mqtt: receive()
Mqtt --> FooCmdReciver: get_message()
ControlSystem --> ControlSystem: ParseMessage()
ControlSystem --> MainEngine
MainEngine --> Motor: <move>(time_ms)
Motor --> MainEngine
MainEngine --> ControlSystem
ControlSystem --> Mqtt
Mqtt --> ControlSystem: send_message(text)

User -->  Telegram_bot : handle_message()
Telegram_bot --> Move: buffer
Move --> ControlSystem: commander()
ControlSystem --> FooCmdReciver: run()
FooCmdReciver --> Mqtt: receive()
Mqtt --> FooCmdReciver: get_message()
ControlSystem --> ControlSystem: ParseMessage()
ControlSystem --> MainEngine
MainEngine --> Motor: <move>(time_ms)
Motor --> MainEngine
MainEngine --> ControlSystem
ControlSystem --> Mqtt
Mqtt --> ControlSystem: send_message(text)
Telegram_bot --> Telegram_bot: pop_order()


@enduml