@startuml

actor "Пользователь" as User
actor "Сервер" as Server
actor "Дозатор" as Extruder
actor "Бот" as Bot

rectangle "Камера" as Camera{
  
  (Получить координаты бота) as get_bot_location
  (Получить координаты дозатора) as get_extruder_location
  (Получить координаты пользователя) as get_user_location

  get_bot_location <-- Server
  get_extruder_location <-- Server
  get_user_location <-- Server
}

(Выбор кофе) as choose_coffee
(Вызов бота) as call_bot

(Составить маршрут бот - дозатор / пользователь) as create_route
(Отправить маршрут боту) as send_route
(Добавить заказ в очередь) as add_order

(Начать разлив) as start_pouring
(Остановить разлив) as stop_pouring

(Двигаться вперёд) as move_forward
(Двигаться назад) as move_back
(Повернуть направо) as turn_right
(Повернуть налево) as turn_left

User --> choose_coffee
choose_coffee --> call_bot

Server --> add_order
Server --> create_route
Server --> send_route

Extruder --> start_pouring
Extruder --> stop_pouring

Bot --> move_forward
Bot --> move_back
Bot --> turn_left
Bot --> turn_right





@enduml
